### ISSUE TITLE
You could be taking risk for no reason

### ISSUE THREAD

**Issue by sushrut111** [rayarindam2111/Co-WIN-automated-slot-booking#10]
Hey,

Chose this way because I think this is the way I could reach you.
Good work man!

However, you are distributing your google messaging extension through zip file - and people are installing it without fair knowledge (I believe many of them are using it, and that's a win for you and I congratulate you for that!)

Now this very thing, gives you (the extension) access to read their bank OTPs. I know your intentions are good and you want to help people - but if something bad happens, fingers could be pointed at you for no reason, right? You will have to prove your innocence. Fair that you can prove that any time, in fact anyone can verify the code, but you will have to face that in the first place.

I hope you are aware of potential troubles.

Cheers.

**Comment by rayarindam2111** [comment]
Hi Sushrut,

First of all, thank you so much for taking the time out to explore the project!

I agree with you when you say that the extension being packed as a compressed file and shipped to people might create a sense of distrust if anything goes wrong - and the specifics of the same wouldn't be of importance if it does. However, the target audience (people who actually come to Github, walk through the entirety of the readme, set up Google Messages and install the extension) would be hard-pressed not to believe that the solution itself is quite technical (no matter how simply it is presented to them, through easily reproducible steps). If that is indeed the case, I find it natural that they would understand the necessity of implementing such a solution, especially if it is well documented and the steps are clearly outlined. As you correctly pointed out, people can always revert back to the code - if they believe this would not serve their purpose, they can choose not to use it. How people use this entire thing is completely up to them - I'm sure you would agree that we, as developers, can only do so much about informing people about using the applications that we design. 

Anyway, to end off the rambling, I'm sure you have noticed that the extension only considers messages that come from senders ending with 'NHPSMS' for obtaining the OTPs. A number of similar projects for booking slots on Co-win already exist - [covid-vaccine-booking](https://github.com/bombardier-gif/covid-vaccine-booking) being a popular example.

If you have any further suggestions, I'd be more than happy to discuss with you. Do let me know.

Cheers!

**Comment by sushrut111** [comment]
No doubt on your intentions bhai!
I understand what you mean -  but I know people who do not know "g" in github using similar things - even apk - giving full potential access to phone.

Anyway, it was a great discussion with you, thanks!
