### ISSUE TITLE
Firefox port for the addon.

### ISSUE THREAD

**Issue by sbstratos79** [rayarindam2111/Co-WIN-automated-slot-booking#11]
Hey. I ported your extension to firefox and signed it myself so I could use it on my pc. Mozilla doesn't allow installation of unsigned extensions on stable release of Firefox anymore. I hope you won't mind. I can share the xpi file if u want.

**Comment by rayarindam2111** [comment]
Sure thing!

**Comment by sbstratos79** [comment]
Here's the link to the xpi file. [Firefox Addon](https://addons.mozilla.org/firefox/downloads/file/3789548/cowin_slot_booking_gmessage-0.0.5-fx.xpi)

**Comment by rayarindam2111** [comment]
> Here's the link to the xpi file. [Firefox Addon](https://addons.mozilla.org/firefox/downloads/file/3789548/cowin_slot_booking_gmessage-0.0.5-fx.xpi)

The link appears to be broken.

**Comment by sbstratos79** [comment]
Oh sh.. I tried opening the link in incognito mode and it worked so I assumed it would work for everyone since it's a direct link to the xpi file on Mozilla add-ons website. Seems like it'll only work for me since I was logged in to my Firefox account. Even in incognito, of all things!  [Here's another link.](https://ttm.sh/FLo.xpi )

**Comment by rayarindam2111** [comment]
> Oh sh.. I tried opening the link in incognito mode and it worked so I assumed it would work for everyone since it's a direct link to the xpi file on Mozilla add-ons website. Seems like it'll only work for me since I was logged in to my Firefox account. Even in incognito, of all things! [Here's another link.](https://ttm.sh/FLo.xpi)

Looks good! 😄
