### ISSUE TITLE
Code was running successfully but didnt book

### ISSUE THREAD

**Issue by Mohit208111** [rayarindam2111/Co-WIN-automated-slot-booking#12]
@rayarindam2111 
My code was running and there were 350 vaccines available but it didnt book the slot for me unfortunately.

Please help, I have trying to book since 2 weeks now. Could you check the logs or something?

The slots were available for 2 minutes. The code checked for slot every 15 seconds. How in the world it didnt book for me.. please help me
really really need your help

![image](https://user-images.githubusercontent.com/85695321/121554486-d756dd80-ca2f-11eb-92a1-fffd9dfbb210.png)

**Comment by Mohit208111** [comment]
Could I call you ? Or could you please call me? 8792662246. really really need your help

**Comment by Mohit208111** [comment]
The slots were available for 2 minutes. The code checked for slot every 15 seconds. How in the world it didnt book for me.. please help me

**Comment by Mohit208111** [comment]
Bhai.. please do help !!! <folded hand wala emoji>

**Comment by rayarindam2111** [comment]
> @rayarindam2111 
> My code was running and there were 350 vaccines available but it didnt book the slot for me unfortunately.
> 
> Please help, I have trying to book since 2 weeks now. Could you check the logs or something?
> 
> The slots were available for 2 minutes. The code checked for slot every 15 seconds. How in the world it didnt book for me.. please help me
> Could I call you ? Or could you please call me? 8792662246. really really need your help
> 
> 
> ![image](https://user-images.githubusercontent.com/85695321/121554486-d756dd80-ca2f-11eb-92a1-fffd9dfbb210.png)
> 

That should not happen. Are you sure you set the options correctly? Maybe you selected the wrong dates or the wrong vaccine?

**Comment by Mohit208111** [comment]
No.. i absolutely checked everything atleast 5 times again because this was my first checkpoint.. 

Can we please speak over call once? Please??

**Comment by rayarindam2111** [comment]
I don't think I'll be available over call. Sorry about that.

The update interval is a minimum of 10seconds for the vaccine registration after the increment of the rate limits put in place last week. I see that you've set the update frequency to a value even less than that. It could've been the case that slots were completely booked out in that interval. You can try incrementing the update frequency.

**Comment by Mohit208111** [comment]
1. So if we consider that bar to be 100%. at which percent should keep the 'update frequency' point.
2. Sometimes OTP is delayed - in that case would your code keep running in background and even though it is not logged in, could it give update stamp at the bottom? Or would it fail?

**Comment by rayarindam2111** [comment]
1. You can keep it at 100%.

2. Even if the OTP verification service fails once, it automatically keeps retrying in the background. You don't have to do anything about it.
