### ISSUE TITLE
As per package.json we can book through Umang also??

### ISSUE THREAD

**Issue by ansi82** [rayarindam2111/Co-WIN-automated-slot-booking#2]

**Comment by rayarindam2111** [comment]
Yes. Please check out the updated version. It features a completely automated version for booking vaccine slots.

**Comment by ansi82** [comment]
It will work through extension same as cowin ?

**Comment by ansi82** [comment]
Error detected failed to login
![Screenshot (35)](https://user-images.githubusercontent.com/84778690/120013482-690d2680-bffe-11eb-871d-07e50992a8a5.png)

**Comment by rayarindam2111** [comment]
Please retry. The UMANG website is down quite frequently. Also ensure you have followed all the setup steps correctly.

**Comment by ansi82** [comment]
In this case it is impossible to book through Umang website

**Comment by rayarindam2111** [comment]
No, not really. The UMANG login is a one time process and the authorisation token persists for 24hours. The booking itself is unaffected by this issue. This is verified and a number of people have already booked slots through this process.

**Comment by ansi82** [comment]
I am going through same process as you have mentioned, one time it went ahead after that extension (select state) page came and state and all was non selective. And after that it is failed to login is showing whenever i try to login through autoslot...

**Comment by ansi82** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/84778690/120026299-80a0db00-c00f-11eb-9541-22e75626c094.png)

**Comment by rayarindam2111** [comment]
Could you open the Network tab in Developer tools and see if your network requests are failing? And send a screenshot?

**Comment by ansi82** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/84778690/120027901-97e0c800-c011-11eb-953c-ddc864525fe6.png)

**Comment by rayarindam2111** [comment]
Click on the generateOTP and confirmOTP requests and show me the received response (Preview tab)?

**Comment by ansi82** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/84778690/120055021-27f23200-c051-11eb-8b73-43617421db5c.png)

**Comment by ansi82** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/84778690/120055060-5a9c2a80-c051-11eb-83eb-2561cbef7265.png)

**Comment by ansi82** [comment]
As per extension it opens AX-NHPSMS to read OTP, but otp comes always from different XX-NHPSMS, you can check screenshot also
![Screenshot (39)](https://user-images.githubusercontent.com/84778690/120055209-28d79380-c052-11eb-8936-b92cf86928e3.png)

**Comment by ansi82** [comment]
A better view of **### Error Detected** with confirm OTP and generate OTP (As you have asked)
![Screenshot (41)](https://user-images.githubusercontent.com/84778690/120055534-6ccb9800-c054-11eb-9c4b-748b1d71a471.png)

![Screenshot (40)](https://user-images.githubusercontent.com/84778690/120055527-5d4c4f00-c054-11eb-8100-46b7bf880673.png)

**Comment by rayarindam2111** [comment]
> As per extension it opens AX-NHPSMS to read OTP, but otp comes always from different XX-NHPSMS, you can check screenshot also
> ![Screenshot (39)](https://user-images.githubusercontent.com/84778690/120055209-28d79380-c052-11eb-8936-b92cf86928e3.png)
> 

Oh, got it. Select the conversation where the OTPs are coming then. I assumed it was AX-NHPSMS for most people, but I'll update that. You can manually select the conversation where the OTP is coming after the Google Messages page opens. Hope this solves the issue.

**Comment by ansi82** [comment]
I am not able to do login
It shows - Error Detected
                   Failed to login. Please try again
(Umang S*cks)

**Comment by ansi82** [comment]
Extension Error
![Screenshot (43)](https://user-images.githubusercontent.com/84778690/120062187-6eaa5100-c07e-11eb-8301-b48f67d5e170.png)

**Comment by rayarindam2111** [comment]
> I am not able to do login
> It shows - Error Detected
>                    Failed to login. Please try again
> (Umang S*cks)

Yeah the Umang server can be frustrating at times.

**Comment by rayarindam2111** [comment]
> Extension Error
> ![Screenshot (43)](https://user-images.githubusercontent.com/84778690/120062187-6eaa5100-c07e-11eb-8301-b48f67d5e170.png)
> 

This comes if you selected a different conversation in Google Messages. It searches for the text 'Co-Win', but if you move to a different conversation that cannot be found. Anyway, I've updated the extension. You can re-download and try again.

**Comment by rayarindam2111** [comment]
> I am not able to do login
> It shows - Error Detected
>                    Failed to login. Please try again
> (Umang S*cks)

Also, please remember that the time gap between generation of OTPs has to be more than 3 minutes.

**Comment by ansi82** [comment]
Finally it went through, automated vaccine registration extension (which was provided earlier)
So we have to leave this page open for 24hrs as you have told token exist for 24hrs.
 So I don't have to do anything but just to be online..??

**Comment by rayarindam2111** [comment]
Yes. Thanks for your response. I am closing this thread now. :)

**Comment by ansi82** [comment]
ok, thanks for so much help....

**Comment by rayarindam2111** [comment]
Please consider leaving a star if this helped you. 😊

**Comment by ansi82** [comment]
After your public folder update
Again same problem occurs 👎 
Error Detected
Failed to login. Please try again

**Comment by rayarindam2111** [comment]
Could you reinstall the updated plugin and try again? I just booked slots for two people through this, so it's definitely working for me.

**Comment by ansi82** [comment]
You can see yourself
https://user-images.githubusercontent.com/84778690/120072146-e80e6780-c0af-11eb-8bff-6ef0bd00d1f3.mp4

**Comment by ansi82** [comment]
i have reinstall the plugin and now this is coming
![Screenshot (44)](https://user-images.githubusercontent.com/84778690/120072717-d1b5db00-c0b2-11eb-89db-13c0ef42f456.png)

**Comment by rayarindam2111** [comment]
What is your Chrome version? This literally has never happened with anyone up until now :/

**Comment by ansi82** [comment]
Version 91.0.4472.77 (Official Build) (64-bit)
![Screenshot (46)](https://user-images.githubusercontent.com/84778690/120093323-12573800-c137-11eb-9ad6-d0486710f5cd.png)

**Comment by ansi82** [comment]
However it is working fine now, maybe umang server problem... 👍
