### ISSUE TITLE
Beneficiary

### ISSUE THREAD

**Issue by subashjain** [rayarindam2111/Co-WIN-automated-slot-booking#3]
cant select beneficiary 1,2,3,or 4 it shows all, and from today to until how many days it will search

**Comment by subashjain** [comment]
if possible try to add date option to select

**Comment by rayarindam2111** [comment]
Yeah you can only select one individual beneficiary or all beneficiaries. The number of days depends on the Co-Win slot release. Any number of days from the current day for which slots are released will be considered.

**Comment by rayarindam2111** [comment]
> if possible try to add date option to select

Yeah, I'm working on it. Thanks for the suggestion :)

**Comment by subashjain** [comment]
> Yeah you can only select one individual beneficiary or all beneficiaries. The number of days depends on the Co-Win slot release. Any number of days from the current day for which slots are released will be considered.

i have added 4 beneficiaries in my mobile number and all are vaccinated, but for two 2nd dose due on 31st may so if i select all it will book for those 2 only right?

**Comment by rayarindam2111** [comment]
No, it will try to book for all. You have to individually select one person in different tries.

**Comment by subashjain** [comment]
> No, it will try to book for all. You have to individually select one person in different tries.

okay but no option to select single person , it is showing only All to select

**Comment by subashjain** [comment]
![image](https://user-images.githubusercontent.com/983641/120064663-ff872980-c08a-11eb-9560-b8bd6b019971.jpeg)

**Comment by rayarindam2111** [comment]
You need to add beneficiaries on the Co-Win website first for them to show up here.

**Comment by subashjain** [comment]
> You need to add beneficiaries on the Co-Win website first for them to show up here.

yes bro already added after that only I'm trying
already added four

**Comment by rayarindam2111** [comment]
Please retry, this is not supposed to happen. If it still does not work, could you show me what your console window is showing?

**Comment by subashjain** [comment]
![image](https://user-images.githubusercontent.com/983641/120070459-459eb600-c0a8-11eb-85d8-0a7334450b79.jpeg)

**Comment by subashjain** [comment]
> Please retry, this is not supposed to happen. If it still does not work, could you show me what your console window is showing?

i didn't understand? i have to run any command line ? I'm using it in windows10 ,  Please help

**Comment by rayarindam2111** [comment]
No, press F12 on your keyboard before doing anything. A window would open up.  After that, login and send the screenshot.

**Comment by subashjain** [comment]
> No, press F12 on your keyboard before doing anything. A window would open up. After that, login and send the screenshot.

okay bro yes after pressing F12 now its showing beneficiaries, so before logging in we have to use F12, right?

**Comment by subashjain** [comment]
![image](https://user-images.githubusercontent.com/983641/120070967-a0391180-c0aa-11eb-9b47-c147a3d9156d.jpeg)

**Comment by rayarindam2111** [comment]
You are getting network errors. This is an issue with Umang servers.

**Comment by rayarindam2111** [comment]
Or you can try lowering the update frequency.

**Comment by subashjain** [comment]
> Or you can try lowering the update frequency.

ok 10seconds

**Comment by rayarindam2111** [comment]
> > Or you can try lowering the update frequency.
> 
> ok 10seconds

Sure. I'm closing this issue then.

**Comment by rayarindam2111** [comment]
Added the option to select custom set of beneficiaries. :)

**Comment by rayarindam2111** [comment]
Date selection feature has also been added! 😄
