### ISSUE TITLE
Exposed secrets ( Not sure )

### ISSUE THREAD

**Issue by wise-introvert** [rayarindam2111/Co-WIN-automated-slot-booking#7]
Saw these variables:
https://github.com/rayarindam2111/Co-WIN-automated-slot-booking/blob/fa286f381e6627b35aa85020fcb35c32b289b641/public/umang-cowin.js#L25
https://github.com/rayarindam2111/Co-WIN-automated-slot-booking/blob/fa286f381e6627b35aa85020fcb35c32b289b641/public/umang-cowin.js#L26

If these are secrets to the Umang api/crawler, you might wanna hide them in an external file ( `.env` )

**Comment by rayarindam2111** [comment]
No, none of these are secrets. These only select the correct service for Co-Win. The only secret is the token that is generated by the server at runtime.
