### ISSUE TITLE
Rate limit issue after 20 refreshes

### ISSUE THREAD

**Issue by shivaslifzz** [rayarindam2111/Co-WIN-automated-slot-booking#9]
Today evening cowin api setup rate limit 20 refreshes onlt

![image](https://user-images.githubusercontent.com/61616987/120693219-5dba6f00-c4c6-11eb-92ad-92548af8e840.png)

at 11:48:05 it reaches 20 refreshes after that script is not updating

**Comment by rayarindam2111** [comment]
Still this is not an issue. The number of requests is linked to the token generated - if tokens are generated more frequently, the rate can be increased. Have incorporated this change into the code in the latest commits. :)

**Comment by shivaslifzz** [comment]
This changes happened yesterday only bro please check from your end if you don't see this issue then close it

**Comment by rayarindam2111** [comment]
Yeah I checked today morning only. Thank you!
